Traceback (most recent call last):
  File "/Users/wernph/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/wernph/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/wernph/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/wernph/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/wernph/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/wernph/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/wernph/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/wernph/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np # is needed to calculate the logarithm

# find the minimum of dep_delay
min_delay = fly_viz2['dep_delay'].min() 
# substract the min_delay from dep_delay in each row
fly_viz2["dep_delay"] = fly_viz2["dep_delay"] - min_delay 
fly_viz2 = fly_viz2[fly_viz2.dep_delay!=0] # to avoid loc(0) in the following example

# create a new column that contains the logarithm of the previously subtracted dep_delay
fly_viz2.loc['log_dep_delay', np.log(fly_viz2['dep_delay'])]

# Visualize Data - Box Plot with log scale
alt.Chart(fly_viz2, width=200).mark_boxplot().encode( 
  alt.X('x'),
  alt.Y('log_dep_delay:Q').scale(zero=False)
).properties( 
    width=350,
    height=250
    )
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/indexes/base.py:3621[0m, in [0;36mIndex.get_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   3620[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3621[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mcasted_key[49m[43m)[49m
[1;32m   3622[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/_libs/index.pyx:136[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/_libs/index.pyx:144[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mpandas/_libs/index_class_helper.pxi:41[0m, in [0;36mpandas._libs.index.Int64Engine._check_type[0;34m()[0m

[0;31mKeyError[0m: 'log_dep_delay'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[14], line 10[0m
[1;32m      7[0m fly_viz2 [38;5;241m=[39m fly_viz2[fly_viz2[38;5;241m.[39mdep_delay[38;5;241m!=[39m[38;5;241m0[39m] [38;5;66;03m# to avoid loc(0) in the following example[39;00m
[1;32m      9[0m [38;5;66;03m# create a new column that contains the logarithm of the previously subtracted dep_delay[39;00m
[0;32m---> 10[0m [43mfly_viz2[49m[38;5;241;43m.[39;49m[43mloc[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mlog_dep_delay[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mnp[49m[38;5;241;43m.[39;49m[43mlog[49m[43m([49m[43mfly_viz2[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mdep_delay[39;49m[38;5;124;43m'[39;49m[43m][49m[43m)[49m[43m][49m
[1;32m     12[0m [38;5;66;03m# Visualize Data - Box Plot with log scale[39;00m
[1;32m     13[0m alt[38;5;241m.[39mChart(fly_viz2, width[38;5;241m=[39m[38;5;241m200[39m)[38;5;241m.[39mmark_boxplot()[38;5;241m.[39mencode( 
[1;32m     14[0m   alt[38;5;241m.[39mX([38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m),
[1;32m     15[0m   alt[38;5;241m.[39mY([38;5;124m'[39m[38;5;124mlog_dep_delay:Q[39m[38;5;124m'[39m)[38;5;241m.[39mscale(zero[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m   (...)[0m
[1;32m     18[0m     height[38;5;241m=[39m[38;5;241m250[39m
[1;32m     19[0m     )

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/indexing.py:961[0m, in [0;36m_LocationIndexer.__getitem__[0;34m(self, key)[0m
[1;32m    959[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_scalar_access(key):
[1;32m    960[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_get_value([38;5;241m*[39mkey, takeable[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_takeable)
[0;32m--> 961[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_tuple[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m    962[0m [38;5;28;01melse[39;00m:
[1;32m    963[0m     [38;5;66;03m# we by definition only have the 0th axis[39;00m
[1;32m    964[0m     axis [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39maxis [38;5;129;01mor[39;00m [38;5;241m0[39m

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/indexing.py:1140[0m, in [0;36m_LocIndexer._getitem_tuple[0;34m(self, tup)[0m
[1;32m   1138[0m [38;5;28;01mwith[39;00m suppress(IndexingError):
[1;32m   1139[0m     tup [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_expand_ellipsis(tup)
[0;32m-> 1140[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_lowerdim[49m[43m([49m[43mtup[49m[43m)[49m
[1;32m   1142[0m [38;5;66;03m# no multi-index, so validate all of the indexers[39;00m
[1;32m   1143[0m tup [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_validate_tuple_indexer(tup)

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/indexing.py:867[0m, in [0;36m_LocationIndexer._getitem_lowerdim[0;34m(self, tup)[0m
[1;32m    863[0m [38;5;28;01mfor[39;00m i, key [38;5;129;01min[39;00m [38;5;28menumerate[39m(tup):
[1;32m    864[0m     [38;5;28;01mif[39;00m is_label_like(key):
[1;32m    865[0m         [38;5;66;03m# We don't need to check for tuples here because those are[39;00m
[1;32m    866[0m         [38;5;66;03m#  caught by the _is_nested_tuple_indexer check above.[39;00m
[0;32m--> 867[0m         section [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_axis[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43mi[49m[43m)[49m
[1;32m    869[0m         [38;5;66;03m# We should never have a scalar section here, because[39;00m
[1;32m    870[0m         [38;5;66;03m#  _getitem_lowerdim is only called after a check for[39;00m
[1;32m    871[0m         [38;5;66;03m#  is_scalar_access, which that would be.[39;00m
[1;32m    872[0m         [38;5;28;01mif[39;00m section[38;5;241m.[39mndim [38;5;241m==[39m [38;5;28mself[39m[38;5;241m.[39mndim:
[1;32m    873[0m             [38;5;66;03m# we're in the middle of slicing through a MultiIndex[39;00m
[1;32m    874[0m             [38;5;66;03m# revise the key wrt to `section` by inserting an _NS[39;00m

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/indexing.py:1202[0m, in [0;36m_LocIndexer._getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1200[0m [38;5;66;03m# fall thru to straight lookup[39;00m
[1;32m   1201[0m [38;5;28mself[39m[38;5;241m.[39m_validate_key(key, axis)
[0;32m-> 1202[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_label[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/indexing.py:1153[0m, in [0;36m_LocIndexer._get_label[0;34m(self, label, axis)[0m
[1;32m   1151[0m [38;5;28;01mdef[39;00m [38;5;21m_get_label[39m([38;5;28mself[39m, label, axis: [38;5;28mint[39m):
[1;32m   1152[0m     [38;5;66;03m# GH#5667 this will fail if the label is not present in the axis.[39;00m
[0;32m-> 1153[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mobj[49m[38;5;241;43m.[39;49m[43mxs[49m[43m([49m[43mlabel[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/generic.py:3864[0m, in [0;36mNDFrame.xs[0;34m(self, key, axis, level, drop_level)[0m
[1;32m   3862[0m             new_index [38;5;241m=[39m index[loc]
[1;32m   3863[0m [38;5;28;01melse[39;00m:
[0;32m-> 3864[0m     loc [38;5;241m=[39m [43mindex[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   3866[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(loc, np[38;5;241m.[39mndarray):
[1;32m   3867[0m         [38;5;28;01mif[39;00m loc[38;5;241m.[39mdtype [38;5;241m==[39m np[38;5;241m.[39mbool_:

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/indexes/base.py:3623[0m, in [0;36mIndex.get_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   3621[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_engine[38;5;241m.[39mget_loc(casted_key)
[1;32m   3622[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:
[0;32m-> 3623[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m   3624[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m   3625[0m     [38;5;66;03m# If we have a listlike key, _check_indexing_error will raise[39;00m
[1;32m   3626[0m     [38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise[39;00m
[1;32m   3627[0m     [38;5;66;03m#  the TypeError.[39;00m
[1;32m   3628[0m     [38;5;28mself[39m[38;5;241m.[39m_check_indexing_error(key)

[0;31mKeyError[0m: 'log_dep_delay'
KeyError: 'log_dep_delay'

